#!/usr/bin/env python3
from __future__ import print_function

PKG = 'pyx4'
NAME = 'pyx4_test'

import sys 
import time
import unittest
import os
import csv

import rospy
import rostest
import roslib.scriptutil as scriptutil
from pyx4.msg import pyx4_test as Pyx4_test_msg
from pyx4_base_classes.definitions_pyx4 import MISSION_SPECS

class Pyx4Test(unittest.TestCase):
    def __init__(self, *args):
        super(Pyx4Test, self).__init__(*args)
        self.results = []
        
    def callback(self, data):
        """ Callback function from pyx4_test topic.
        Adds the result to the results list for assertion
        when the mission is completed.
        :param data: pyx4_test message
        """
        self.results[data.test_type].append({'test_type': data.test_type,
                                             'passed': data.passed,
                                             'desc': data.description})

    def test_main(self):
        """ Main testing function. Called automatically by unittest.
        Subscribe to pyx4_test and waits for the mission to finish.
        Then, all the results that have been stored in self.results
        are asserted.
        """
        rospy.Subscriber("pyx4_test/pyx4_test", Pyx4_test_msg, self.callback)
        rospy.init_node(NAME, anonymous=True)
        while not rospy.is_shutdown() and time.time() < TIMEOUT:
            time.sleep(0.1)

        for result in self.results:
            self.assertTrue(result['passed'], msg=result['description'])
        
if __name__ == '__main__':
    mission_file = os.path.join(MISSION_SPECS, sys.argv[1])
    with open(mission_file, 'r') as f:
        reader = csv.DictReader(f)
        TIMEOUT = sum([int(dic['timeout']) for dic in reader]) * 1.1
        
    rostest.rosrun(PKG, NAME, Pyx4Test, sys.argv)
